<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>WireTests</AssemblyName>
    <ValheimInstall Condition="'$(ValheimInstall)' == ''">C:\Program Files (x86)\Steam\steamapps\common\Valheim</ValheimInstall>
    <ValheimManaged>$(ValheimInstall)\valheim_Data\Managed</ValheimManaged>
    <BepInExCore>$(ValheimInstall)\BepInEx\core</BepInExCore>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\AdaptiveNet.csproj" />
    <Reference Include="assembly_valheim">
      <HintPath>$(ValheimManaged)\assembly_valheim.dll</HintPath>
    </Reference>
    <Reference Include="assembly_utils">
      <HintPath>$(ValheimManaged)\assembly_utils.dll</HintPath>
    </Reference>
    <Reference Include="com.rlabrecque.steamworks.net">
      <HintPath>$(ValheimManaged)\com.rlabrecque.steamworks.net.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(ValheimManaged)\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(ValheimManaged)\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>$(BepInExCore)\BepInEx.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
